### ISSUE TITLE
C++17 standard requested but CXX17 is not defined

### ISSUE THREAD

**Issue by 25280841** [thompsonsed/rcoalescence#1]
How can I fix this?

configure: GDAL: 1.11.4
checking GDAL version >= 2.1.0... yes
configure: C flags: -g -O2 -I.  -I/usr/include/gdal
configure: CPP flags: -I.  -I/usr/include/gdal
configure: CXX flags: -g -O2 -I.  -I/usr/include/gdal
configure: PKG_CXX flags: -I. -I/usr/include/gdal
configure: PKG_C flags:  -I/usr/include/gdal
checking GDAL: /usr/share/gdal/pcs.csv readable... yes
checking gdal_priv.h usability... yes
checking gdal_priv.h presence... yes
checking for gdal_priv.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
configure: creating ./config.status
config.status: creating src/Makevars
** libs
Error in .shlib_internal(args) : 
  C++17 standard requested but CXX17 is not defined
* removing ‘/usr/share/R/library/rcoalescence’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpQi9To1/file71111be99d25/rcoalescence_1.0.0.tar.gz’ had non-zero exit status

**Comment by thompsonsed** [comment]
This indicates that no compiler support C++ 17 was detected. What platform are you installing on? 

A compiler supporting C++17 is required for rcoalescence (e.g. an up-to-date version of gcc).

If you are on Linux you can install by `sudo apt-get install build-essential` (or equivalent on your distro).

For MacOS you the easiest method will be to use `brew install gcc` (if you have homebrew installed) - you might need xtools as well (`xcode-select --install`).

Following this, you might need to then set `CXX17` to the name of your compiler in your `~/.R/Makevars` file.

**Comment by 25280841** [comment]
Thanks a lot!

The platform is centos8, and I enabled the devoolset8 before running R, "scl enable devtoolset-8 bash"
I set the "CXX17" flag in "~/.R/Makevars" , and the error was fixed.

CXX17FLAGS=-O3 -march=native -mtune=native -fPIC
CXX17 = g++ -std=c++1y


But there is another error about sqlite3 :

It looks like the final test didn't pass.

**** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘rcoalescence’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib64/R/library/rcoalescence/libs/rcoalescence.so':
  /usr/local/lib64/R/library/rcoalescence/libs/rcoalescence.so: undefined symbol: sqlite3_bind_int
Error: loading failed
Execution halted
ERROR: loading failed**


what I have installed are below:
/usr/bin/sqlite3
/usr/bin/sqlite3-dbf
/usr/include/sqlite3.h
/usr/include/sqlite3ext.h
/usr/include/sqlite3x
/usr/include/sqlite3x/sqlite3x.hpp
/usr/include/sqlite3x/sqlite3x_settings_db.hpp
/usr/lib64/libsqlite3.so
/usr/lib64/libsqlite3.so.0
/usr/lib64/libsqlite3.so.0.8.6
/usr/lib64/libsqlite3bak
/usr/lib64/libsqlite3x.so
/usr/lib64/libsqlite3x.so.1
/usr/lib64/libsqlite3x.so.1.0.0

and I tried to set link from the probable file, it just not works!

**Comment by thompsonsed** [comment]
Hmm looks like a problem with the sqlite installation. Have you installed the dev version of sqlite3? The package will be called something like sqlite-devel. Did the RSQLite dependency install successfully?

I've just pushed a change to the main branch that might help as well - could you try with the updated version?
